CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(254) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(60) NOT NULL
);

CREATE TABLE Address (
  id SERIAL PRIMARY KEY,
  street VARCHAR(200) NOT NULL,
  number INT NOT NULL,
  district VARCHAR(200) NOT NULL,
  cep VARCHAR(10) NOT NULL
);

CREATE TABLE Events (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  user_id INT NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
  address_id INT NOT NULL REFERENCES Address(id) ON DELETE CASCADE,
  event_time TIME NOT NULL,
  event_date DATE NOT NULL,
  description VARCHAR(250)
);
